# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commands',
            new_name='Comments',
        ),
    ]
