# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160928_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_tex',
            new_name='article_text',
        ),
    ]
